# Generated by Django 5.0.3 on 2024-04-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv1', '0004_music_music_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='view',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
